# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('security_token', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
