# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='post_uploads/%Y/%m/%d/')),
                ('file_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='posts.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='upload_date',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
