# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170510_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='fileupload',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Algorithm Analysis'), ('2', 'Language Theory'), ('3', 'Mobile Development'), ('4', 'Web Development'), ('5', 'Web Security'), ('6', 'Data Structures'), ('7', 'General Programming')], default='7', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'Java'), ('3', 'C++'), ('4', 'C#'), ('5', 'C'), ('6', 'Assembly'), ('7', 'Javascript')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
