# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170510_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=django_markdown.models.MarkdownField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Algorithm Analysis', 'Algorithm Analysis'), ('Language Theory', 'Language Theory'), ('Mobile Development', 'Mobile Development'), ('Web Development', 'Web Development'), ('Web Security', 'Web Security'), ('Data Structures', 'Data Structures'), ('General Programming', 'General Programming')], default='General Programming', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('C', 'C'), ('Assembly', 'Assembly'), ('Javascript', 'Javascript')], default='C', max_length=100),
        ),
    ]
