# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.Post'),
        ),
    ]
