# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
